/*
 ********************************************************************
 * Licensed Materials - Property of HCL                             *
 *                                                                  *
 * Copyright HCL Software 2021. All Rights Reserved.                *
 *                                                                  *
 * Note to US Government Users Restricted Rights:                   *
 *                                                                  *
 * Use, duplication or disclosure restricted by GSA ADP Schedule    *
 *                                                                  *
 * Author: Emmanuel Palogan                                         *
 * Release Version: v.Q12023                                         *
 ********************************************************************
 */

export const I18N = {
    "en": {
        "pdf.icon.tooltip": "PDF document",
		"switcher.version.tooltip": "Select a version",
        "switcher.language.tooltip": "Select a language",
        "rating.success.alert": "Thank you for your feedback!",
		"rating.no.show": "<b>Have feedback?</b><br/>Google Analytics is used to store comments and ratings. To provide a comment or rating for a topic, click <b>Accept All Cookies</b> or <b>Allow All</b> in Cookie Preferences in the footer of this page.",
        "rating.error.alert": "To submit feedback, first rate or comment on the topic.",
        "rating.star.label": "Rate this topic",
        "rating.comment.label": "Comment on this topic",
        "rating.check.label": 'By clicking this box, you acknowledge that you are NOT a U.S. Federal Government employee or agency, nor are you submitting information with respect to or on behalf of one. HCL provides software and services to U.S. Federal Government customers through its partners Four, Inc. Contact this team at <a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a>. Do not include any personal data in this Comment box.',
        "rating.check.note": '<b>Note:</b> To report a problem or question about the product software, do not use this form. Instead, go to the <a href="https://support.hcltechsw.com/csm">HCL Software Support</a> site.',
		"rating.check.privacy": 'Personal data should not be shared in this comment box. See our <a href="https://www.hcltechsw.com/legal/privacy" target="_block">Privacy Statement</a> to understand how personal data is used.',
        "request.version.error": "Page is not available for the selected version!",
        "request.language.error": "Translation does not exist!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Product Documentation",
		"header.resource.dropdown": "Resources",
		"header.customer.support": "Customer Support",
		"header.community.forums": "Community Forums",
		"feedback.comment.PII.messagealert": "Please remove personal information such as your email address and phone number before clicking Submit.",
		"feedback.comment.alert": "Enter your comments in the comment box.",
		"footer.mail.link": "Share: Email",
		"footer.twitt.link": "Twitter",
		"footer.disclaim.label": "Disclaimer",
		"footer.privacy.label": "Privacy",
		"footer.terms.label": "Terms of use",
		"footer.cookie.label": "Cookie Preferences"
		
    },
    "fr": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Sélectionnez une version",
        "switcher.language.tooltip": "Sélectionnez une langue",
        "rating.success.alert": "Merci pour votre retour !",
		"rating.no.show": "<b>Vous avez des commentaires ?</b><br/>Google Analytics est utilisé pour stocker les commentaires et les évaluations. Pour fournir un commentaire ou une évaluation pour un sujet, cliquez sur <b>Accepter tous les cookies</b> ou <b>Autoriser tout</b> dans les préférences en matière de cookies dans le pied de page de cette page.",
        "rating.error.alert": "Pour nous faire part de votre retour, commencez par attribuer une note ou un commentaire à un sujet.",
        "rating.star.label": "Noter ce sujet",
        "rating.comment.label": "Laisser un commentaire ce sujet",
        "rating.check.label": 'En cochant cette case, vous certifiez ne PAS être employé par le gouvernement fédéral des États-Unis ou par l\'une de ses agences, et que vous n\'envoyez pas ces informations de la part de l\'une de ces entités. HCL fournit des logiciels et des services aux clients du gouvernement fédéral des États-Unis via ses partenaires Four, Inc. Veuillez contacter cette équipe à l\'aide du lien suivant : <a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a>. Votre commentaire ne doit contenir aucune information permettant de vous identifier.',
       "rating.check.note": '<b>Note:</b> Pour signaler un problème ou une question concernant le logiciel du produit, n\'utilisez pas ce formulaire. Rendez-vous plutôt sur le site <a href=\"https://support.hcltechsw.com/csm\">HCL Software Support</a>.',
		"rating.check.privacy": 'Les données personnelles ne doivent pas être partagées dans cette boîte de commentaires. Consultez notre <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">Déclaration de confidentialité</a> pour comprendre comment les données personnelles sont utilisées.',
        "request.version.error": "La traduction n'est pas disponible pour la version sélectionnée !",
        "request.language.error": "La traduction n'existe pas !",
		"header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Documentation produit",
		"header.resource.dropdown": "Ressources",
		"header.customer.support": "Service client",
		"header.community.forums": "Forums communautaires",
		"feedback.comment.PII.messagealert": "Veuillez supprimer les informations personnelles telles que votre adresse e-mail et votre numéro de téléphone avant de cliquer sur Soumettre.",
		"feedback.comment.alert": "Entrez vos commentaires dans la zone de commentaires.",
		"footer.mail.link": "Partager : Courriel",
		"footer.twitt.link": "Twitter",
		"footer.disclaim.label": "Clause de non-responsabilité",
		"footer.privacy.label": "Intimité",
		"footer.terms.label": "Conditions d\'utilisation",
		"footer.cookie.label": "Préférences relatives aux cookies"
		        
    },
    "ja": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "バージョンを選択します",
        "switcher.language.tooltip": "言語の選択",
        "rating.success.alert": "フィードバックをありがとうございます。",
		"rating.no.show": "<b>フィードバックがありますか？</b><br></br>コメントや評価を保存するために、Google Analyticsが使用されています。トピックに対するコメントや評価を提供するには、このページのフッターにあるCookieの設定で<b>Accept All Cookies</b> または <b>Allow All</b> をクリックしてください。",
        "rating.error.alert": "フィードバックを送信するには、まずそのトピックについて評価またはコメントします。",
        "rating.star.label": "このトピックを評価する",
        "rating.comment.label": "このトピックにコメントする",
        "rating.check.label": 'このボックスをクリックすることにより、米国連邦政府の職員または代理人ではないこと、また、その職員または代理人に関してまたは代理として情報を提出していないことを確認したことになります。HCL は、パートナーである Four, Inc を通じて、米国連邦政府の顧客にソフトウェアおよびサービスを提供しています。このチームには <a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a> からお問い合わせください。このコメントボックスには個人データを入力しないでください。',
        "rating.check.note": '<b>注意:</b> 製品ソフトウェアに関する問題や質問を報告するために、このフォームを使用しないでください。代わりに、<a href=\"https://support.hcltechsw.com/csm\">HCL Software Support</a> のサイトにアクセスしてください。',
		"rating.check.privacy": 'このコメント欄では、個人情報を共有しないでください。個人データの使用方法については、<a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">プライバシーステートメント</a>をご覧ください。',
        "request.version.error": "選択したバージョンの翻訳は利用できません。",
        "request.language.error": "翻訳は存在しません。",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "製品ドキュメント",
		"header.resource.dropdown": "リソース",
		"header.customer.support": "顧客サポート",
		"header.community.forums": "コミュニティ フォーラム",
		"feedback.comment.PII.messagealert": "[送信] をクリックする前に、メール アドレスや電話番号などの個人情報を削除してください。",
		"feedback.comment.alert": "コメント ボックスにコメントを入力します。",
		"footer.mail.link": "共有: メール",
		"footer.twitt.link": "ツイッター",
		"footer.disclaim.label": "免責事項",
		"footer.privacy.label": "プライバシー",
		"footer.terms.label": "利用規約",
		"footer.cookie.label": "クッキーの設定"
		
    },
    "ar": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "اختيار نسخة",
        "switcher.language.tooltip": "حدد لغة",
        "rating.success.alert": "شكرًا لك على تعليقك!",
		"rating.no.show": "<b>هل لديك تعليقات؟</b> <br> </br> يُستخدم Google Analytics لتخزين التعليقات والتقييمات. لتقديم تعليق أو تصنيف لموضوع ما ، انقر فوق <b> قبول كافة ملفات تعريف الارتباط </ b> أو <b> السماح للكل </ b> في تفضيلات ملفات تعريف الارتباط في تذييل هذه الصفحة.",
        "rating.error.alert": "لتقديم تعليقك، عليك أولاً تقييم الموضوع أو التعليق عليه.",
        "rating.star.label": "تقييم هذا الموضوع",
        "rating.comment.label": "التعليق على هذا الموضوع",
        "rating.check.label": 'بالنقر فوق هذا المربع ، فإنك تقر بأنك لست موظفًا أو وكالة تابعة للحكومة الفيدرالية الأمريكية ، ولا ترسل معلومات فيما يتعلق أو نيابةً عن أي منها. توفر HCL البرامج والخدمات لعملاء الحكومة الفيدرالية الأمريكية من خلال شركائها Four، Inc.. اتصل بهذا الفريق على <a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a>. لا تقم بتضمين أي بيانات شخصية في مربع التعليق هذا.',
        "rating.check.note": '<b> ملاحظة: </ b> للإبلاغ عن مشكلة أو سؤال حول برنامج المنتج ، لا تستخدم هذا النموذج. بدلاً من ذلك ، انتقل إلى موقع <a href=\"https://support.hcltechsw.com/csm\"> HCL Software Support </a>.',
		"rating.check.privacy": 'يجب عدم مشاركة البيانات الشخصية في مربع التعليق هذا. راجع <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\"> بيان الخصوصية </a> لفهم كيفية استخدام البيانات الشخصية.',
        "request.version.error": "الترجمة غير متوفرة للنسخة المحددة!",
        "request.language.error": "الترجمة غير موجودة!",
        "header.learning.academy": "HCLSoftware U",
	"header.proddoc.brand": "وثائق المنتج",
		"header.resource.dropdown": "موارد",
		"header.customer.support": "دعم العملاء",
		"header.community.forums": "منتديات إجتماعية",
		"feedback.comment.PII.messagealert": "يرجى إزالة المعلومات الشخصية مثل عنوان بريدك الإلكتروني ورقم هاتفك قبل النقر فوق إرسال.",
		"feedback.comment.alert": "أدخل تعليقاتك في مربع التعليق.",
		"footer.mail.link": "مشاركة: البريد الإلكتروني",
		"footer.twitt.link": "تويتر",
		"footer.disclaim.label": "تنصل",
		"footer.privacy.label": "خصوصية",
		"footer.terms.label": "تعليمات الاستخدام",
		"footer.cookie.label": "تفضيلات ملفات تعريف الارتباط"
    },
    "ca": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Seleccionar versió",
        "switcher.language.tooltip": "Seleccioneu un idioma",
        "rating.success.alert": "Gràcies pels vostres comentaris!",
		"rating.no.show": "<b>Teniu comentaris?</b><br/>Google Analytics s\'utilitza per emmagatzemar comentaris i puntuacions. Per proporcionar un comentari o una puntuació d\'un tema, feu clic a <b>Accepta totes les galetes</b> o a <b>Permet-ho tot</b> a Preferències de galetes al peu d\'aquesta pàgina.",
        "rating.error.alert": "Per enviar comentaris, valoreu o comenteu el tema abans.",
        "rating.star.label": "Valorar aquest tema",
        "rating.comment.label": "Comentar aquest tema",
        "rating.check.label": 'En fer clic en aquest quadre, reconeixeu que NO no sou un empleat ni una agència del Govern Federal dels EUA, i que no envieu informació relacionat amb o en nom d\'un/una. HCL ofereix programari i serveis als clients del Govern Federal dels EUA a través del seu soci Four, Inc. Poseu-vos en contacte amb aquest equip a <a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a>. No incloeu cap dada personal en aquest quadre de comentaris.',
        "rating.check.note": '<b>Nota:</b> per informar d\'un problema o pregunta sobre el programari del producte, no utilitzeu aquest formulari. En comptes d\'això, aneu al lloc <a href=\"https://support.hcltechsw.com/csm\">Suport de programari HCL</a>.',
		"rating.check.privacy": 'Les dades personals no s\'han de compartir en aquest quadre de comentaris. Consulteu la nostra <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">Declaració de privadesa</a> per entendre com s\'utilitzen les dades personals.',
        "request.version.error": "La traducció no està disponible per a la versió seleccionada!",
        "request.language.error": "La traducció no existeix!",
        "header.learning.academy": "HCLSoftware U",
		"header.resource.dropdown": "Recursos",
		"header.customer.support": "Atenció al client",
		"header.community.forums": "Fòrums comunitaris",
		"feedback.comment.PII.messagealert": "Si us plau, elimineu la informació personal, com ara la vostra adreça de correu electrònic i el vostre número de telèfon abans de fer clic a Envia.",
		"feedback.comment.alert": "Introduïu els vostres comentaris al quadre de comentaris.",
		"footer.mail.link": "Comparteix: correu electrònic",
		"footer.twitt.link": "Twitter",
		"footer.disclaim.label": "Exempció de responsabilitat",
		"footer.privacy.label": "Privadesa",
		"footer.terms.label": "Condicions d\'ús",
		"footer.cookie.label": "Preferències de cookies"
    },
    "zh_CN": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "选择版本",
        "switcher.language.tooltip": "选择一种语言",
        "rating.success.alert": "感谢您提供的反馈！",
		"rating.no.show": "<b>有反馈吗？</b><br/>Google Analytics 用于存储评论和评分。要为某个主题提供评论或评级，请在此页面页脚的 Cookie 首选项中单击 <b>接受所有 Cookie</b> 或 <b>全部允许</b>。",
        "rating.error.alert": "要提交反馈，首先请评价此主题或对此主题发表评论。",
        "rating.star.label": "评价此主题",
        "rating.comment.label": "对此主题发表评论",
        "rating.check.label": '点击此框即表示您承认您不是美国联邦政府雇员或代理，您也没有提交关于美国联邦政府雇员或代理的信息，或代表美国联邦政府雇员或代理提交信息。HCL 通过其合作伙伴 Four, Inc. 向美国联邦政府客户提供软件和服务。请通过  <a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a> 与此团队联系。请勿在此“评论”框中包含任何个人数据。',
        "rating.check.note": '<b>注意：</b>要报告有关产品软件的问题或疑问，请勿使用此表单。请转至 <a href=\"https://support.hcltechsw.com/csm\">HCL 软件支持</a> 站点。',
		"rating.check.privacy": '不应在此评论框中共享个人数据。请参阅我们的<a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">隐私声明</a>，了解个人数据的使用方式。',
        "request.version.error": "所选版本的翻译不可用！",
        "request.language.error": "翻译不存在！",
        "header.learning.academy": "HCLSoftware U",
			"header.proddoc.brand": "产品文档",
		"header.resource.dropdown": "资源",
		"header.customer.support": "客户支持",
		"header.community.forums": "社区论坛",
		"feedback.comment.PII.messagealert": "在点击提交之前，请删除您的电子邮件地址和电话号码等个人信息。",
		"feedback.comment.alert": "在评论框中输入您的评论。",
		"footer.mail.link": "分享：电子邮件",
		"footer.twitt.link": "推特",
		"footer.disclaim.label": "免责声明",
		"footer.privacy.label": "隐私",
		"footer.terms.label": "使用条款",
		"footer.cookie.label": "Cookie 偏好"
    },
    "zh_TW": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "選取版本",
        "switcher.language.tooltip": "選取語言",
        "rating.success.alert": "感謝您提供意見！",
		"rating.no.show": "<b>有反饋嗎？</b><br/>Google Analytics 用於存儲評論和評分。要為某個主題提供評論或評級，請在此頁面頁腳的 Cookie 首選項中單擊 <b>接受所有 Cookie</b> 或 <b>全部允許</b>。",
        "rating.error.alert": "若要提交意見，請先為主題評分或在主題上留言。",
        "rating.star.label": "為此主題評分",
        "rating.comment.label": "在此主題上留言",
        "rating.check.label": '按下此方塊，即表示您承認自己並非美國聯邦政府的員工，也並不具備美國聯邦政府的身分，而且您也並非遵照美國聯邦政府之意思或代表其提交資訊。HCL 是透過合作夥伴 Four, Inc. 向美國聯邦政府客戶提供軟體和服務。請透過以下連結聯絡此團隊：<a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a>. 請不要在此留言方框中提供個人資料。',
        "rating.check.note": '<b>注意：</b>要報告有關產品軟件的問題或疑問，請勿使用此表單。請轉至 <a href=\"https://support.hcltechsw.com/csm\">HCL 軟件支持</a> 站點。',
		"rating.check.privacy": '不應在此評論框中共享個人數據。請參閱我們的<a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">隱私聲明</a>，了解個人數據的使用方式。',
        "request.version.error": "所選版本未提供翻譯！",
        "request.language.error": "沒有翻譯！",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "產品文檔",
		"header.resource.dropdown": "資源",
		"header.customer.support": "客戶支持",
		"header.community.forums": "社區論壇",
		"feedback.comment.PII.messagealert": "在點擊提交之前，請刪除您的電子郵件地址和電話號碼等個人信息。",
		"feedback.comment.alert": "在評論框中輸入您的評論。",
		"footer.mail.link": "分享：電子郵件",
		"footer.twitt.link": "推特",
		"footer.disclaim.label": "免責聲明",
		"footer.privacy.label": "隱私",
		"footer.terms.label": "使用條款",
		"footer.cookie.label": "Cookie 偏好"
    },
    "cs": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Vyberte verzi",
        "switcher.language.tooltip": "Vyberte jazyk",
        "rating.success.alert": "Děkujeme za vaši zpětnou vazbu!",
		"rating.no.show": "<b>Máte zpětnou vazbu?</b><br/>Google Analytics se používá k ukládání komentářů a hodnocení. Chcete-li k tématu přidat komentář nebo hodnocení, klikněte na <b>Přijmout všechny soubory cookie</b> nebo <b>Povolit vše</b> v Předvolbách souborů cookie v zápatí této stránky.",
        "rating.error.alert": "Pokud chcete odeslat zpětnou vazbu, nejprve ohodnoťte nebo okomentujte téma.",
        "rating.star.label": "Ohodnoťte toto téma",
        "rating.comment.label": "Okomentujte toto téma",
        "rating.check.label": 'Kliknutím na toto políčko potvrzujete, že NEJSTE zaměstnancem nebo úřadem federální vlády USA ani neodesíláte informace s ohledem na ně nebo jejich jménem. Zákazníkům z řad federální vlády USA poskytuje společnost HCL software a služby prostřednictvím svých partnerů Four, Inc. Tento tým můžete kontaktovat na adrese <a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a>. Do pole Komentář nezadávejte žádné osobní údaje.',
         "rating.check.note": '<b>Poznámka:</b> Chcete-li nahlásit problém nebo dotaz ohledně softwaru produktu, nepoužívejte tento formulář. Místo toho přejděte na stránku <a href=\"https://support.hcltechsw.com/csm\">Softwarová podpora HCL</a>.',
		"rating.check.privacy": 'V tomto poli komentáře by neměly být sdíleny osobní údaje. Chcete-li pochopit, jak jsou osobní údaje používány, přečtěte si naše <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">Prohlášení o ochraně osobních údajů</a>.',
        "request.version.error": "Pro vybranou verzi není k dispozici překlad!",
        "request.language.error": "Překlad neexistuje!",
        "header.learning.academy": "HCLSoftware U",
		"header.resource.dropdown": "Zdroje",
		"header.customer.support": "Zákaznická podpora",
		"header.community.forums": "Komunitní fóra",
		"feedback.comment.PII.messagealert": "Před kliknutím na Odeslat prosím odstraňte osobní údaje, jako je e-mailová adresa a telefonní číslo.",
		"feedback.comment.alert": "Do pole komentáře zadejte své komentáře.",
		"footer.mail.link": "Sdílet: Email",
		"footer.twitt.link": "Cvrlikání",
		"footer.disclaim.label": "Zřeknutí se odpovědnosti",
		"footer.privacy.label": "Soukromí",
		"footer.terms.label": "Podmínky použití",
		"footer.cookie.label": "Předvolby souborů cookie"
    },
    "nl": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Selecteer een versie",
        "switcher.language.tooltip": "Selecteer een taal",
        "rating.success.alert": "Bedankt voor je feedback!",
		"rating.no.show": "<b>Heeft u feedback?</b> <br/>Google Analytics wordt gebruikt om opmerkingen en beoordelingen op te slaan. Om een opmerking of waardering te geven voor een onderwerp, klikt u op <b>Accept All Cookies</b> of <b>Allow All</b> in Cookievoorkeuren in de voettekst van deze pagina.",
        "rating.error.alert": "Om feedback te geven, beoordeel eerst of geef commentaar op het onderwerp.",
        "rating.star.label": "Beoordeel dit onderwerp",
        "rating.comment.label": "Reageer op dit onderwerp",
        "rating.check.label": 'Door op dit vakje te klikken, erkent u dat u GEEN werknemer of instantie van de Amerikaanse federale overheid bent, noch dat u informatie indient met betrekking tot of namens een dergelijke werknemer of instantie. HCL levert software en diensten aan klanten van de Amerikaanse federale overheid via haar partners Four, Inc. Neem contact op met dit team via <a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a>. Vermeld geen persoonlijke gegevens in dit reactieveld.',
        "rating.check.note": '<b>Note:</b> Gebruik dit formulier niet om een probleem of vraag over de productsoftware te melden. Ga in plaats daarvan naar de <a href=\"https://support.hcltechsw.com/csm\">HCL Software Support</a> site.',
		"rating.check.privacy": 'Persoonlijke gegevens mogen niet worden gedeeld in dit commentaarvak. Zie onze <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">Privacyverklaring</a> om te begrijpen hoe persoonlijke gegevens worden gebruikt.',
        "request.version.error": "Vertaling is niet beschikbaar voor de geselecteerde versie!",
        "request.language.error": "Vertaling bestaat niet!",
        "header.learning.academy": "HCLSoftware U",
	"header.proddoc.brand": "Productdocumentatie",
		"header.resource.dropdown": "Bronnen",
		"header.customer.support": "Klantenservice",
		"header.community.forums": "gemeenschapsforums",
		"feedback.comment.PII.messagealert": "Verwijder persoonlijke informatie zoals uw e-mailadres en telefoonnummer voordat u op Verzenden klikt.",
		"feedback.comment.alert": "Voer uw opmerkingen in het opmerkingenveld in.",
		"footer.mail.link": "Deel: e-mail",
		"footer.twitt.link": "Twitteren",
		"footer.disclaim.label": "Vrijwaring",
		"footer.privacy.label": "Privacy",
		"footer.terms.label": "Gebruiksvoorwaarden",
		"footer.cookie.label": "Cookievoorkeuren"
    },
    "fi": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Valitse versio",
        "switcher.language.tooltip": "Valitse jokin kieli",
        "rating.success.alert": "Kiitos palautteestasi!",
		"rating.no.show": "<b>Onko sinulla palautetta?</b><br/>Google Analyticsia käytetään kommenttien ja arvioiden tallentamiseen. Jos haluat antaa kommentin tai arvion aiheelle, napsauta <b>Hyväksy kaikki evästeet</b> tai <b>Salli kaikki</b> Evästeasetuksissa tämän sivun alatunnisteessa.",
        "rating.error.alert": "Lähetä palautetta arvioimalla aihe tai kommentoimalla sitä.",
        "rating.star.label": "Arvioi tämä aihe",
        "rating.comment.label": "Kommentoi tätä aihetta",
        "rating.check.label": 'Valitsemalla tämän ruudun vakuutat, että ET ole Yhdysvaltain liittovaltion valtionhallinnon työntekijä tai virasto etkä lähetä tietoja sen puolesta tai siihen liittyviä tietoja. HCL toimittaa ohjelmistoa ja palveluita Yhdysvaltain liittovaltion valtionhallinnon asiakkaille kumppaninsa, Four, Inc:n kautta. Ota yhteyttä tähän ryhmään osoitteessa <a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a>. Älä sisällytä mitään henkilötietoja tähän kommenttiruutuun.',
        "rating.check.note": '<b>Huomaa:</b> Älä käytä tätä lomaketta ilmoittaaksesi ongelmasta tai kysymyksestä tuotteen ohjelmistosta. Siirry sen sijaan <a href=\"https://support.hcltechsw.com/csm\">HCL-ohjelmistotukisivustolle</a>.',
		"rating.check.privacy": 'Henkilötietoja ei saa jakaa tässä kommenttikentässä. Katso <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">tietosuojalausunnostamme</a>, kuinka henkilötietoja käytetään.',
        "request.version.error": "Käännöstä ei ole saatavilla valitulle versiolle!",
        "request.language.error": "Käännöstä ei ole olemassa!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Tuotedokumentaatio",
		"header.resource.dropdown": "Resurssit",
		"header.customer.support": "Asiakaspalvelu",
		"header.community.forums": "Yhteisön foorumit",
		"feedback.comment.PII.messagealert": "Poista henkilökohtaiset tiedot, kuten sähköpostiosoitteesi ja puhelinnumerosi, ennen kuin napsautat Lähetä.",
		"feedback.comment.alert": "Kirjoita kommenttisi kommenttikenttään.",
		"footer.mail.link": "Jaa: Sähköposti",
		"footer.twitt.link": "Viserrys",
		"footer.disclaim.label": "Vastuuvapauslauseke",
		"footer.privacy.label": "Yksityisyys",
		"footer.terms.label": "Käyttöehdot",
		"footer.cookie.label": "Evästeasetukset"
    },
    "de": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Wählen Sie eine Version aus",
        "switcher.language.tooltip": "Sprache auswählen",
        "rating.success.alert": "Vielen Dank für Ihr Feedback!",
		"rating.no.show": "<b>Haben Sie Feedback?</b><br/>Google Analytics wird verwendet, um Kommentare und Bewertungen zu speichern. Um einen Kommentar oder eine Bewertung für ein Thema abzugeben, klicken Sie in den Cookie-Einstellungen in der Fußzeile dieser Seite auf <b>Alle Cookies akzeptieren</b> oder <b>Alle zulassen</b>.",
        "rating.error.alert": "Um ein Feedback abzugeben, bewerten oder kommentieren Sie zunächst das Thema.",
        "rating.star.label": "Dieses Thema bewerten",
        "rating.comment.label": "Kommentar zu diesem Thema",
        "rating.check.label": 'Indem Sie dieses Kästchen anklicken, bestätigen Sie, dass Sie KEIN Mitarbeiter oder keine Behörde der US-Bundesregierung sind und dass Sie keine Informationen in Bezug auf oder im Namen einer solchen Behörde übermitteln. HCL bietet Software und Services für Kunden der US-Bundesregierung über seinen Partner Four, Inc. an. Wenden Sie sich an dieses Team unter <a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a>. Bitte geben Sie in diesem Kommentarfeld keine persönlichen Daten an.',
       "rating.check.note": '<b>Hinweis:</b> Um ein Problem oder eine Frage zur Produktsoftware zu melden, verwenden Sie dieses Formular nicht. Rufen Sie stattdessen die Website <a href=\"https://support.hcltechsw.com/csm\">HCL Software Support</a> auf.',
		"rating.check.privacy": 'Personenbezogene Daten sollten in diesem Kommentarfeld nicht geteilt werden. Lesen Sie unsere <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">Datenschutzerklärung</a>, um zu verstehen, wie personenbezogene Daten verwendet werden.',
        "request.version.error": "Für die ausgewählte Version ist keine Übersetzung verfügbar!",
        "request.language.error": "Es ist keine Übersetzung vorhanden!",
		"header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Produktdokumentation",
		"header.resource.dropdown": "Ressourcen",
		"header.customer.support": "Kundendienst",
		"header.community.forums": "Community-Foren",
		"feedback.comment.PII.messagealert": "Bitte entfernen Sie persönliche Informationen wie Ihre E-Mail-Adresse und Telefonnummer, bevor Sie auf „Senden“ klicken.",
		"feedback.comment.alert": "Geben Sie Ihre Kommentare in das Kommentarfeld ein.",
		"footer.mail.link": "Teilen: E-Mail",
		"footer.twitt.link": "Twitter",
		"footer.disclaim.label": "Haftungsausschluss",
		"footer.privacy.label": "Privatsphäre",
		"footer.terms.label": "Nutzungsbedingungen",
		"footer.cookie.label": "Cookie-Einstellungen"
		
    },
    "iw": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "בחירת גרסה",
        "switcher.language.tooltip": "בחרו שפה",
        "rating.success.alert": "תודה על המשוב!",
		"rating.no.show": "",
        "rating.error.alert": "לשליחת המשוב, דרג או הוסף הערה לנושא תחילה.",
        "rating.star.label": "דרג נושא זה",
        "rating.comment.label": "הוסף הערה לנושא זה",
        "rating.check.label": 'סימון תיבה זו מהווה אישור שאינך עובד או שייך לסוכנות של הממשל הפדרלי של ארה"ב וכן שאינך שולח מידע לגבי אדם או סוכנות השייכים לממשל הפדרלי או מטעמם. HCL מספקת תוכנה ושירותים ללקוחות השייכים לממשל הפדרלי של ארה"ב באמצעות שותפתה, Four, Inc. פנה לצוות זה בכתובת <a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a>. אין לכלול נתונים אישיים כלשהם בתיבת הערות זו.',
        "rating.check.note": '',
		"rating.check.privacy": "",
        "request.version.error": "אין תרגום זמין לגרסה שנבחרה!",
        "request.language.error": "לא קיים תרגום!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "תיעוד המוצר",
		"header.resource.dropdown": "אֶמְצָעִי",
		"header.customer.support": "שירות לקוחות",
		"header.community.forums": "פורומים קהילתיים",
		"feedback.comment.PII.messagealert": "אנא הסר מידע אישי כגון כתובת הדוא\"ל ומספר הטלפון שלך לפני שתלחץ על שלח.",
		"feedback.comment.alert": "הכנס את ההערות שלך בתיבת ההערות.",
		"footer.mail.link": "שתף: אימייל",
		"footer.twitt.link": "טוויטר",
		"footer.disclaim.label": "כתב ויתור",
		"footer.privacy.label": "פְּרָטִיוּת",
		"footer.terms.label": "תנאי שימוש",
		"footer.cookie.label": "העדפות קובצי Cookie"
    },
    "it": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Selezionare una versione",
        "switcher.language.tooltip": "Selezionare una lingua",
        "rating.success.alert": "Grazie per il feedback.",
		"rating.no.show": "<b>Avete commenti?</b> <br/>Per memorizzare commenti e valutazioni viene utilizzato Google Analytics. Per fornire un commento o una valutazione per un argomento, fare clic su <b>Accetta tutti i cookie</b> o <b>Consenti tutti</b> nelle Preferenze sui cookie nel piè di pagina di questa pagina.",
        "rating.error.alert": "Per inviare un feedback è necessario lasciare un commento o una valutazione sull'argomento.",
        "rating.star.label": "Valutare questo argomento",
        "rating.comment.label": "Lasciare un commento su questo argomento",
        "rating.check.label": 'Selezionando questa casella, l\'utente riconosce di NON essere un dipendente o un\'agenzia del governo federale degli Stati Uniti, né di inviare informazioni rispetto a o per conto di uno di essi. HCL fornisce software e servizi ai clienti del governo federale degli Stati Uniti attraverso i suoi partner Four, Inc. Per contattare questo gruppo, visitare la pagina Web <a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a>. Non includere dati personali in questa casella commento.',
         "rating.check.note": '<b>Nota:</b> Per segnalare un problema o una domanda sul software del prodotto, non utilizzare questo modulo. Si consiglia di visitare il sito <a href=\"https://support.hcltechsw.com/csm\">HCL Software Support</a>.',
		"rating.check.privacy": 'I dati personali non devono essere condivisi in questa casella di commento. Consultate la nostra <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">Dichiarazione sulla privacy</a> per capire come vengono utilizzati i dati personali.',
        "request.version.error": "Nessuna traduzione disponibile per la versione selezionata.",
        "request.language.error": "Traduzione inesistente.",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Documentazione del prodotto",
		"header.resource.dropdown": "Risorse",
		"header.customer.support": "Servizio Clienti",
		"header.community.forums": "Forum della comunità",
		"feedback.comment.PII.messagealert": "Rimuovere le informazioni personali come l\'indirizzo e-mail e il numero di telefono prima di fare clic su Invia.",
		"feedback.comment.alert": "Inserisci i tuoi commenti nella casella dei commenti.",
		"footer.mail.link": "Condividi: e-mail",
		"footer.twitt.link": "Cinguettio",
		"footer.disclaim.label": "Disclaimer",
		"footer.privacy.label": "Riservatezza",
		"footer.terms.label": "Termini di utilizzo",
		"footer.cookie.label": "Preferenze cookie"
    },
    "ko": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "버전을 선택합니다",
        "switcher.language.tooltip": "언어 선택",
        "rating.success.alert": "피드백을 제공해 주셔서 감사합니다!",
		"rating.no.show": "<b>피드백이 있으신가요?</b> <br/>Google 애널리틱스는 댓글과 평점을 저장하는 데 사용됩니다. 주제에 대한 의견이나 평가를 제공하려면 이 페이지의 바닥글에서 <b>모든 쿠키 허용 또는 쿠키</b> 기본 설정에서 <b>모두 허용</b>을 클릭합니다.",
        "rating.error.alert": "피드백을 제출하려면 먼저 주제에 대해 평가하거나 댓글을 작성하십시오.",
        "rating.star.label": "이 주제 평가하기",
        "rating.comment.label": "이 주제에 댓글 작성하기",
        "rating.check.label": '이 상자를 클릭하여 본인이 미국 연방 정부 직원이나 에이전시가 아님 또는 이와 관련이 있거나 이를 대표하여 정보를 제출하는 것이 아님을 확인합니다. HCL은 파트너사 Four, Inc.를 통해 미국 연방 정부 고객에게 소프트웨어 및 서비스를 제공합니다. <a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a>에서 이 팀에게 문의하십시오. 이 댓글 상자에 어떠한 개인 데이터도 포함하지 마십시오.',
         "rating.check.note": '<b>메모:</b> 제품 소프트웨어에 대한 문제나 질문을 보고하려면 이 양식을 사용하지 마십시오. 대신 <a\"https://support.hcltechsw.com/csm\">HCL 소프트웨어 지원 사이트로 이동하십시오</a>.',
		"rating.check.privacy": '이 댓글 상자에서 개인 데이터를 공유해서는 안 됩니다. 개인 데이터가 어떻게 사용되는지 이해하려면 <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">개인 정보 보호 정책을 참조하십시오</a>.',
        "request.version.error": "선택한 버전에는 번역이 제공되지 않습니다!",
        "request.language.error": "번역이 없습니다!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "제품 문서",
		"header.resource.dropdown": "리소스",
		"header.customer.support": "고객 지원",
		"header.community.forums": "커뮤니티 포럼",
		"feedback.comment.PII.messagealert": "제출을 클릭하기 전에 이메일 주소 및 전화 번호와 같은 개인 정보를 제거하십시오.",
		"feedback.comment.alert": "의견 상자에 의견을 입력합니다.",
		"footer.mail.link": "공유: 이메일",
		"footer.twitt.link": "지저귀다",
		"footer.disclaim.label": "면책 조항",
		"footer.privacy.label": "사생활",
		"footer.terms.label": "이용 약관",
		"footer.cookie.label": "쿠키 환경 설정"
    },
    "pl": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Wybierz wersję",
        "switcher.language.tooltip": "Wybierz język",
        "rating.success.alert": "Dziękujemy za przesłanie opinii.",
		"rating.no.show": "<b>Masz opinię?</b><br/>Usługa Google Analytics służy do przechowywania komentarzy i ocen. Aby dodać komentarz lub ocenę do tematu, kliknij <b>Akceptuj wszystkie pliki cookie</b> lub <b>Zezwalaj na wszystkie</b> w Preferencjach plików cookie w stopce tej strony.",
        "rating.error.alert": "Aby przesłać opinię, najpierw oceń lub skomentuj temat.",
        "rating.star.label": "Oceń temat",
        "rating.comment.label": "Skomentuj temat",
        "rating.check.label": 'Zaznaczając to pole, potwierdzasz, że NIE jesteś pracownikiem ani agencją rządu federalnego USA i nie przekazujesz informacji w jego imieniu ani na jego temat. Firma HCL dostarcza oprogramowanie i świadczy usługi dla rządu federalnego USA we współpracy z firmą Four, Inc. Aby skontaktować się z jej zespołem, odwiedź stronę <a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a>. W polu komentarza nie należy podawać żadnych informacji osobistych.',
        "rating.check.note": '<b>Uwaga:</b> Aby zgłosić problem lub pytanie dotyczące oprogramowania produktu, nie korzystaj z tego formularza. Zamiast tego przejdź do witryny <a href=\"https://support.hcltechsw.com/csm\">HCL Software Support</a>.',
		"rating.check.privacy": 'W tym polu komentarza nie należy udostępniać danych osobowych. Zapoznaj się z naszym <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">Oświadczeniem o ochronie prywatności</a>, aby zrozumieć, w jaki sposób wykorzystywane są dane osobowe.',
        "request.version.error": "Tłumaczenie nie jest dostępne w wybranej wersji.",
        "request.language.error": "Tłumaczenie nie istnieje.",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Dokumentacja produktu",
		"header.resource.dropdown": "Zasoby",
		"header.customer.support": "Obsługa klienta",
		"header.community.forums": "Fora społecznościowe",
		"feedback.comment.PII.messagealert": "Przed kliknięciem Prześlij usuń dane osobowe, takie jak adres e-mail i numer telefonu.",
		"feedback.comment.alert": "Wpisz swoje uwagi w polu komentarza.",
		"footer.mail.link": "Udostępnij: e-mail",
		"footer.twitt.link": "Świergot",
		"footer.disclaim.label": "Zastrzeżenie",
		"footer.privacy.label": "Prywatność",
		"footer.terms.label": "Warunki korzystania",
		"footer.cookie.label": "Preferencje plików cookie"
    },
    "pt_BR": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Selecione uma versão",
        "switcher.language.tooltip": "Selecione um idioma",
        "rating.success.alert": "Obrigado pelo seu comentário!",
		"rating.no.show": "<b>Tem feedback?</b> <br/>O Google Analytics é usado para armazenar comentários e classificações. Para fornecer um comentário ou classificação para um tópico, clique em <b>Aceitar todos os cookies</b> ou <b>permitir que todos em</b> preferências de cookies no rodapé desta página.",
        "rating.error.alert": "Para enviar comentários, primeiro classifique ou comente no tópico.",
        "rating.star.label": "Classifique este tópico",
        "rating.comment.label": "Comente este tópico",
        "rating.check.label": 'Ao clicar nesta caixa, você reconhece que NÃO é um funcionário ou agência do Governo Federal dos Estados Unidos, nem está enviando informações a respeito de ou em nome de algum desses. A HCL fornece software e serviços para clientes do Governo Federal dos EUA por meio de seus parceiros Four, Inc. Entre em contato com esta equipe em <a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a>. Não inclua nenhum dado pessoal nesta caixa de comentários.',
        "rating.check.note": '<b>nota:</b> Para relatar um problema ou questionar sobre o software do produto, não use este formulário. Em vez disso, vá para o site de suporte de software <a href=\"https://support.hcltechsw.com/csm\">HCL</a>.',
		"rating.check.privacy": 'Os dados pessoais não devem ser compartilhados nesta caixa de comentários. Consulte nossa <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">Privacy Statement</a> para entender como os dados pessoais são usados.',
        "request.version.error": "Não existe tradução disponível para a versão selecionada!",
        "request.language.error": "Não existe tradução!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Documentação do produto",
		"header.resource.dropdown": "Recursos",
		"header.customer.support": "Suporte ao Cliente",
		"header.community.forums": "Fóruns da Comunidade",
		"feedback.comment.PII.messagealert": "Remova informações pessoais, como seu endereço de e-mail e número de telefone, antes de clicar em Enviar.",
		"feedback.comment.alert": "Insira seus comentários na caixa de comentários.",
		"footer.mail.link": "Compartilhar: E-mail",
		"footer.twitt.link": "Gorjeio",
		"footer.disclaim.label": "Disclaimer",
		"footer.privacy.label": "Privacidade",
		"footer.terms.label": "Termos de uso",
		"footer.cookie.label": "Preferências de cookies"
    },
    "ru": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Выберите версию",
        "switcher.language.tooltip": "Выберите язык",
        "rating.success.alert": "Благодарим за отзыв!",
		"rating.no.show": "<b>Есть обратная связь?</b><br/>Google Analytics используется для хранения комментариев и оценок. Чтобы оставить комментарий или оценить тему, нажмите <b>Принять все файлы cookie</b> или <b>Разрешить все</b> в настройках файлов cookie в нижнем колонтитуле этой страницы.",
        "rating.error.alert": "Чтобы отправить отзыв, сначала оцените или прокомментируйте тему.",
        "rating.star.label": "Оценить тему",
        "rating.comment.label": "Прокомментировать тему",
        "rating.check.label": 'Устанавливая этот флажок, вы признаете, что НЕ являетесь сотрудником федеральных органов США и НЕ отправляете информацию от их имени или в связи с ними. Компания HCL предоставляет программное обеспечение и услуги федеральным органам США через партнера Four, Inc. С ним можно связаться на странице <a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a>. Не указывайте в поле комментария персональные данные.',
        "rating.check.note": '<b>Примечание:</b> Чтобы сообщить о проблеме или вопросе, касающемся программного обеспечения продукта, не используйте эту форму. Вместо этого перейдите к <a href=\"https://support.hcltechsw.com/csm \">Сайт поддержки программного обеспечения HCL</a>.',
		"rating.check.privacy": 'Личные данные не должны разглашаться в этом поле для комментариев. Смотрите наш <a href=\"https://www.hcltechsw.com/legal/privacy \" target=\"_block\">Заявление о конфиденциальности</a> чтобы понять, как используются персональные данные.',
        "request.version.error": "Для выбранной версии нет перевода.",
        "request.language.error": "Нет перевода.",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Документация по продукту",
		"header.resource.dropdown": "Ресурсы",
		"header.customer.support": "служба поддержки клиентов",
		"header.community.forums": "Форумы сообщества",
		"feedback.comment.PII.messagealert": "Пожалуйста, удалите личную информацию, такую как ваш адрес электронной почты и номер телефона, прежде чем нажать кнопку Отправить.",
		"feedback.comment.alert": "Введите свои комментарии в поле для комментариев.",
		"footer.mail.link": "Поделиться: Электронная почта",
		"footer.twitt.link": "Твиттер",
		"footer.disclaim.label": "Оговорка",
		"footer.privacy.label": "Конфиденциальность",
		"footer.terms.label": "Условия использования",
		"footer.cookie.label": "Настройки файлов cookie"
    },
    "es": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Seleccione una versión",
        "switcher.language.tooltip": "Seleccione un idioma",
        "rating.success.alert": "¡Le agradecemos sus comentarios!",
		"rating.no.show": "<b>¿Tienes algún comentario?</b><br/>Google Analytics se utiliza para almacenar comentarios y valoraciones. Para proporcionar un comentario o valoración de un tema, haga clic en <b>Aceptar todas las cookies</b> o <b>Permitir todas</b> en Preferencias de cookies en el pie de página de esta página.",
        "rating.error.alert": "Para enviar comentarios, califique o comente el tema primero.",
        "rating.star.label": "Calificar este tema",
        "rating.comment.label": "Comentar este tema",
        "rating.check.label": 'Al pulsar en este cuadro, reconoce que NO es un empleado ni una agencia del Gobierno Federal de EE. UU., y que no envía información respecto a o en nombre de uno/una. HCL ofrece software y servicios a los clientes del Gobierno Federal de EE. UU. a través de su socio Four, Inc. Póngase en contacto con este equipo en <a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a>. No incluya ningún dato personal en este cuadro de comentarios.',
         "rating.check.note": '<b>Nota:</b> Para informar de un problema o pregunta sobre el software del producto, no utilice este formulario. En su lugar, diríjase al sitio <a href=\"https://support.hcltechsw.com/csm\">Soporte de software de HCL</a>.',
		"rating.check.privacy": 'Los datos personales no deben ser compartidos en esta caja de comentarios. Consulte nuestra <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">Declaración de privacidad</a> para entender cómo se utilizan los datos personales.',
        "request.version.error": "¡La traducción no está disponible para la versión seleccionada!",
        "request.language.error": "¡La traducción no existe!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Documentación del producto",
		"header.resource.dropdown": "Recursos",
		"header.customer.support": "Atención al cliente",
		"header.community.forums": "Foros de la comunidad",
		"feedback.comment.PII.messagealert": "Elimine la información personal, como su dirección de correo electrónico y número de teléfono, antes de hacer clic en Enviar.",
		"feedback.comment.alert": "Ingrese sus comentarios en el cuadro de comentarios.",
		"footer.mail.link": "Compartir: Correo electrónico",
		"footer.twitt.link": "Gorjeo",
		"footer.disclaim.label": "Descargo de responsabilidad",
		"footer.privacy.label": "Privacidad",
		"footer.terms.label": "Términos de Uso",
		"footer.cookie.label": "Preferencias de cookies"
    },
    "th": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "เลือกเวอร์ชัน",
        "switcher.language.tooltip": "เลือกภาษา",
        "rating.success.alert": "ขอบคุณสำหรับข้อเสนอแนะของคุณ!",
		"rating.no.show": "<b>มีความคิดเห็นไหม</b><br/>Google Analytics ใช้เพื่อเก็บความคิดเห็นและการให้คะแนน หากต้องการแสดงความคิดเห็นหรือให้คะแนนหัวข้อ ให้คลิก <b>ยอมรับคุกกี้ทั้งหมด</b> หรือ <b>อนุญาตทั้งหมด</b> ในการตั้งค่าคุกกี้ที่ส่วนท้ายของหน้านี้",
        "rating.error.alert": "หากต้องการส่งข้อเสนอแนะ โปรดให้คะแนนหรือแสดงข้อเสนอแนะในหัวข้อก่อน",
        "rating.star.label": "ให้คะแนนหัวข้อนี้",
        "rating.comment.label": "แสดงความคิดเห็นในหัวข้อนี้",
        "rating.check.label": 'การคลิกช่องนี้แสดงว่าคุณรับทราบว่าคุณไม่ใช่พนักงานหรือหน่วยงานของรัฐบาลกลางของสหรัฐฯ และคุณไม่ได้ส่งข้อมูลเกี่ยวกับหรือในนามของหน่วยงานใดหน่วยงานหนึ่ง HCL ให้บริการซอฟต์แวร์และบริการแก่ลูกค้าของรัฐบาลกลางของสหรัฐฯ ผ่านพันธมิตรของ Four, Inc. ติดต่อทีมนี้ที่ <a href="https://hcltechsw.com/resources/us-government-contact">https://hcltechsw.com/resources/us-government-contact</a> อย่าใส่ข้อมูลส่วนบุคคลใดๆ ในช่องแสดงความคิดเห็นนี้',
        "rating.check.note": '<b>หมายเหตุ:</b> หากต้องการรายงานปัญหาหรือคำถามเกี่ยวกับซอฟต์แวร์ของผลิตภัณฑ์ โปรดอย่าใช้แบบฟอร์มนี้ ให้ไปที่เว็บไซต์<a href=\"https://support.hcltechsw.com/csm\">HCL Software Support</a>',
		"rating.check.privacy": 'ไม่ควรแชร์ข้อมูลส่วนบุคคลในช่องแสดงความคิดเห็นนี้ ดู<a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">คำชี้แจงสิทธิ์ส่วนบุคคล</a>ของเราเพื่อทำความเข้าใจวิธีการใช้ข้อมูลส่วนบุคคล',
        "request.version.error": "ไม่มีการแปลสำหรับเวอร์ชันที่เลือก!",
        "request.language.error": "ไม่มีการแปล!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "เอกสารกำกับสินค้า",
		"header.resource.dropdown": "ทรัพยากร",
		"header.customer.support": "สนับสนุนลูกค้า",
		"header.community.forums": "ฟอรัมชุมชน",
		"feedback.comment.PII.messagealert": "โปรดลบข้อมูลส่วนบุคคล เช่น ที่อยู่อีเมลและหมายเลขโทรศัพท์ของคุณออกก่อนที่จะคลิกส่ง",
		"feedback.comment.alert": "ป้อนความคิดเห็นของคุณในช่องแสดงความคิดเห็น",
		"footer.mail.link": "แบ่งปัน: อีเมล์",
		"footer.twitt.link": "ทวิตเตอร์",
		"footer.disclaim.label": "ข้อจำกัดความรับผิดชอบ",
		"footer.privacy.label": "ความเป็นส่วนตัว",
		"footer.terms.label": "ข้อกำหนดการใช้งาน",
		"footer.cookie.label": "การตั้งค่าคุกกี้"
    },
	"bg": {
		"pdf.icon.tooltip": "",
		"switcher.version.tooltip": "Изберете версия",
        "switcher.language.tooltip": "Изберете език",
        "rating.success.alert": "Благодарим Ви за обратната връзка!",
		"rating.no.show": "<b>Имате ли обратна връзка?</b><br/>Google Анализ се използва за съхраняване на коментари и оценки. За да предоставите коментар или оценка за дадена тема, щракнете върху <b>Приемам всички бисквитки</b> или <b>Разрешаване на всички</b> в Предпочитания за бисквитки в долния колонтитул на тази страница.",
        "rating.error.alert": "За да изпратите обратна връзка, първо оценете или коментирайте темата.",
        "rating.star.label": "Оценете тази тема",
        "rating.comment.label": "Коментирайте тази тема",
        "rating.check.label": 'Като щракнете върху това поле, вие потвърждавате, че НЕ сте служител или агенция на федералното правителство на САЩ, нито предоставяте информация по отношение или от името на такъв. HCL предоставя софтуер и услуги на клиенти на федералното правителство на САЩ чрез своите партньори Four, Inc. Свържете се с този екип на адрес <a href=\"https://hcltechsw.com/resources/us-government-contact\">https://hcltechsw.com /resources/us-government-contact</a>. Не включвайте никакви лични данни в това поле за коментар.',
        "rating.check.note": '<b>Забележка:</b> За да съобщите за проблем или въпрос относно софтуера на продукта, не използвайте този формуляр. Вместо това отидете на сайта <a href=\"https://support.hcltechsw.com/csm\">Поддръжка на софтуер на HCL</a>.',
		"rating.check.privacy": 'Личните данни не трябва да се споделят в това поле за коментари. Вижте нашата <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">Декларация за поверителност</a>, за да разберете как се използват личните данни.',
        "request.version.error": "Страницата не е налична за избраната версия!",
        "request.language.error": "Превод не съществува!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Продуктова документация",
		"header.resource.dropdown": "Ресурси",
		"header.customer.support": "Поддръжка на клиенти",
		"header.community.forums": "Форуми на общността",
		"feedback.comment.PII.messagealert": "Моля, премахнете личната информация, като вашия имейл адрес и телефонен номер, преди да щракнете върху Изпращане.",
		"feedback.comment.alert": "Въведете вашите коментари в полето за коментари.",
		"footer.mail.link": "Споделяне: Имейл",
		"footer.twitt.link": "Twitter",
		"footer.disclaim.label": "Опровержение",
		"footer.privacy.label": "поверителност",
		"footer.terms.label": "Условия за ползване",
		"footer.cookie.label": "Предпочитания за бисквитки"
    },
	 "da": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Vælg en version",
        "switcher.language.tooltip": "Vælg et sprog",
        "rating.success.alert": "Tak for din feedback!",
		"rating.no.show": "<b>Har du feedback?</b><br/>Google Analytics bruges til at gemme kommentarer og vurderinger. For at give en kommentar eller bedømmelse til et emne skal du klikke på <b>Accepter alle cookies</b> eller <b>Tillad alle</b> i Cookie-indstillinger i sidefoden på denne side.",
        "rating.error.alert": "For at indsende feedback skal du først vurdere eller kommentere emnet.",
        "rating.star.label": "Bedøm dette emne",
        "rating.comment.label": "Kommenter dette emne",
        "rating.check.label": 'Ved at klikke på denne boks anerkender du, at du IKKE er en amerikansk føderal regeringsansat eller et agentur, og at du heller ikke indsender oplysninger med hensyn til eller på vegne af en. HCL leverer software og tjenester til kunder i den amerikanske føderale regering gennem sine partnere Four, Inc. Kontakt dette team på <a href=\"https://hcltechsw.com/resources/us-government-contact\">https://hcltechsw.com /ressourcer/us-government-contact</a>. Medtag ingen personlige data i dette kommentarfelt.',
        "rating.check.note": '<b>Bemærk:</b> Brug ikke denne formular for at rapportere et problem eller spørgsmål om produktsoftwaren. Gå i stedet til <a href=\"https://support.hcltechsw.com/csm\">HCL Software Support</a>-siden.',
		"rating.check.privacy": 'Personlige data bør ikke deles i dette kommentarfelt. Se vores <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">erklæring om beskyttelse af personlige oplysninger</a> for at forstå, hvordan personlige data bruges.',
        "request.version.error": "Siden er ikke tilgængelig for den valgte version!",
        "request.language.error": "Oversættelse findes ikke!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Produktdokumentation",
		"header.resource.dropdown": "Ressourcer",
		"header.customer.support": "Kunde support",
		"header.community.forums": "Fællesskabsfora",
		"feedback.comment.PII.messagealert": "Fjern venligst personlige oplysninger såsom din e-mailadresse og telefonnummer, før du klikker på Send.",
		"feedback.comment.alert": "Indtast dine kommentarer i kommentarfeltet.",
		"footer.mail.link": "Del: E-mail",
		"footer.twitt.link": "Twitter",
		"footer.disclaim.label": "Ansvarsfraskrivelse",
		"footer.privacy.label": "Privatliv",
		"footer.terms.label": "Vilkår for brug",
		"footer.cookie.label": "Cookie-præferencer"
    },
	"he": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "בחר גרסה",
        "switcher.language.tooltip": "בחר שפה",
        "rating.success.alert": "תודה על המשוב שלך!",
		"rating.no.show": "<b>יש לך משוב?</b><br/>Google Analytics משמש לאחסון הערות ודירוגים. כדי לספק הערה או דירוג לנושא, לחץ על <b>קבל את כל העוגיות</b> או <b>אפשר הכל</b> בהעדפות קובצי Cookie בכותרת התחתונה של דף זה.",
        "rating.error.alert": "כדי לשלוח משוב, דרג ראשון או הערה על הנושא.",
        "rating.star.label": "דרג נושא זה",
        "rating.comment.label": "הערה בנושא זה",
        "rating.check.label": 'על ידי לחיצה על תיבה זו, אתה מאשר שאינך עובד או סוכנות בממשל הפדרלי של ארה\"ב, וגם אינך מוסר מידע לגבי או בשמו. HCL מספקת תוכנה ושירותים ללקוחות ממשלת ארה\"ב באמצעות שותפיה Four, Inc. צור קשר עם צוות זה בכתובת <a href=\"https://hcltechsw.com/resources/us-government-contact\">https://hcltechsw.com /resources/us-government-contact</a>. אל תכלול נתונים אישיים בתיבת הערות זו.',
        "rating.check.note": '<b>הערה:</b> כדי לדווח על בעיה או שאלה לגבי תוכנת המוצר, אל תשתמש בטופס זה. במקום זאת, עבור אל אתר <a href=\"https://support.hcltechsw.com/csm\">תמיכה בתוכנת HCL</a>.',
		"rating.check.privacy": 'אין לשתף נתונים אישיים בתיבת הערות זו. עיין ב<a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">הצהרת הפרטיות</a> שלנו כדי להבין כיצד נעשה שימוש בנתונים אישיים.',
        "request.version.error": "הדף אינו זמין עבור הגרסה שנבחרה!",
        "request.language.error": "תרגום לא קיים!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "תיעוד המוצר",
		"header.resource.dropdown": "אֶמְצָעִי",
		"header.customer.support": "שירות לקוחות",
		"header.community.forums": "פורומים קהילתיים",
		"feedback.comment.PII.messagealert": "אנא הסר מידע אישי כגון כתובת הדוא\"ל ומספר הטלפון שלך לפני שתלחץ על שלח.",
		"feedback.comment.alert": "הכנס את ההערות שלך בתיבת ההערות.",
		"footer.mail.link": "שתף: אימייל",
		"footer.twitt.link": "טוויטר",
		"footer.disclaim.label": "כתב ויתור",
		"footer.privacy.label": "פְּרָטִיוּת",
		"footer.terms.label": "תנאי שימוש",
		"footer.cookie.label": "העדפות קובצי Cookie"
    },
	 "hr": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Odaberite verziju",
        "switcher.language.tooltip": "Odaberite jezik",
        "rating.success.alert": "Hvala vam na povratnim informacijama!",
		"rating.no.show": "<b>Imate povratne informacije?</b><br/>Google Analytics se koristi za pohranu komentara i ocjena. Da biste dali komentar ili ocjenu za temu, kliknite <b>Prihvati sve kolačiće</b> ili <b>Dopusti sve</b> u Postavkama kolačića u podnožju ove stranice.",
        "rating.error.alert": "Da biste poslali povratne informacije, prvo ocijenite ili komentirajte temu.",
        "rating.star.label": "Ocijenite ovu temu",
        "rating.comment.label": "Komentirajte ovu temu",
        "rating.check.label": 'Klikom na ovaj okvir potvrđujete da NISTE zaposlenik ili agencija savezne vlade SAD-a, niti da dostavljate informacije u vezi ili u ime istih. HCL pruža softver i usluge korisnicima savezne vlade SAD-a putem svojih partnera Four, Inc. Kontaktirajte ovaj tim na <a href=\"https://hcltechsw.com/resources/us-government-contact\">https://hcltechsw.com /resources/us-government-contact</a>. Nemojte uključivati nikakve osobne podatke u ovaj okvir za komentare.',
        "rating.check.note": '<b>Napomena:</b> da biste prijavili problem ili pitanje o softveru proizvoda, nemojte koristiti ovaj obrazac. Umjesto toga idite na web-mjesto <a href=\"https://support.hcltechsw.com/csm\">Podrška za HCL softver</a>.',
		"rating.check.privacy": 'Osobni podaci se ne smiju dijeliti u ovom polju za komentare. Pogledajte našu <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">Izjavu o privatnosti</a> da biste razumjeli kako se koriste osobni podaci.',
        "request.version.error": "Stranica nije dostupna za odabranu verziju!",
        "request.language.error": "Prijevod ne postoji!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Dokumentacija proizvoda",
		"header.resource.dropdown": "Resursi",
		"header.customer.support": "Korisnička podrška",
		"header.community.forums": "Forumi zajednice",
		"feedback.comment.PII.messagealert": "Uklonite osobne podatke kao što su adresa e-pošte i broj telefona prije nego što kliknete Pošalji.",
		"feedback.comment.alert": "Unesite svoje komentare u okvir za komentare.",
		"footer.mail.link": "Dijeli: E-pošta",
		"footer.twitt.link": "Cvrkut",
		"footer.disclaim.label": "Odricanje",
		"footer.privacy.label": "Privatnost",
		"footer.terms.label": "Uvjeti korištenja",
		"footer.cookie.label": "Postavke kolačića"
    },
	"hu": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Válasszon verziót",
        "switcher.language.tooltip": "Válasszon nyelvet",
        "rating.success.alert": "Köszönjük a visszajelzést!",
		"rating.no.show": "<b>Van visszajelzése?</b><br/>A Google Analytics a megjegyzések és értékelések tárolására szolgál. Ha megjegyzést vagy értékelést szeretne adni egy témához, kattintson az <b>Összes cookie elfogadása</b> vagy az <b>Összes engedélyezése</b> lehetőségre a Cookie-beállításokban az oldal láblécében.",
        "rating.error.alert": "Ha visszajelzést szeretne küldeni, először értékelje vagy kommentálja a témát.",
        "rating.star.label": "Értékelje ezt a témát",
        "rating.comment.label": "Hozzászólás ehhez a témához",
        "rating.check.label": 'A négyzetre kattintva Ön tudomásul veszi, hogy NEM az Egyesült Államok szövetségi kormányának alkalmazottja vagy ügynöksége, és nem ad meg információkat az egyikkel kapcsolatban vagy nevében. A HCL szoftvereket és szolgáltatásokat nyújt az Egyesült Államok szövetségi kormányának ügyfelei számára partnerein, az Four, Inc.-en keresztül. Lépjen kapcsolatba ezzel a csapattal: <a href=\"https://hcltechsw.com/resources/us-government-contact\">https://hcltechsw.com /resources/us-government-contact</a>. Ne tüntessen fel személyes adatokat ebben a megjegyzés rovatban.',
        "rating.check.note": '<b>Megjegyzés:</b> A termékszoftverrel kapcsolatos probléma vagy kérdés bejelentéséhez ne használja ezt az űrlapot. Ehelyett keresse fel a <a href=\"https://support.hcltechsw.com/csm\">HCL szoftvertámogatási</a> webhelyet.',
		"rating.check.privacy": 'Személyes adatok nem oszthatók meg ebben a megjegyzés rovatban. Tekintse meg <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">Adatvédelmi nyilatkozatunkat</a> a személyes adatok felhasználásának megértéséhez.',
        "request.version.error": "Az oldal a kiválasztott verzióhoz nem érhető el!",
        "request.language.error": "A fordítás nem létezik!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Termékdokumentáció",
		"header.resource.dropdown": "Erőforrások",
		"header.customer.support": "Vevőszolgálat",
		"header.community.forums": "Közösségi fórumok",
		"feedback.comment.PII.messagealert": "Kérjük, távolítsa el a személyes adatokat, például e-mail címét és telefonszámát, mielőtt a Küldés gombra kattintana.",
		"feedback.comment.alert": "Írja be megjegyzéseit a megjegyzés rovatba.",
		"footer.mail.link": "Megosztás: E-mail",
		"footer.twitt.link": "Twitter",
		"footer.disclaim.label": "Jogi nyilatkozat",
		"footer.privacy.label": "Magánélet",
		"footer.terms.label": "Használati feltételek",
		"footer.cookie.label": "Cookie-beállítások"
    },
	 "no": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Velg en versjon",
        "switcher.language.tooltip": "Velg et språk",
        "rating.success.alert": "Takk for din tilbakemelding!",
		"rating.no.show": "<b>Har du tilbakemelding?</b><br/>Google Analytics brukes til å lagre kommentarer og vurderinger. For å gi en kommentar eller vurdering for et emne, klikk <b>Godta alle informasjonskapsler</b> eller <b>Tillat alle</b> i Innstillinger for informasjonskapsler i bunnteksten på denne siden.",
        "rating.error.alert": "For å sende inn tilbakemelding, førsteklasses eller kommenter emnet.",
        "rating.star.label": "Vurder dette emnet",
        "rating.comment.label": "Kommenter dette emnet",
        "rating.check.label": 'Ved å klikke på denne boksen erkjenner du at du IKKE er en ansatt eller et byrå i USAs føderale regjering, og at du heller ikke sender inn informasjon med hensyn til eller på vegne av en. HCL leverer programvare og tjenester til amerikanske føderale myndigheter gjennom sine partnere Four, Inc. Kontakt dette teamet på <a href=\"https://hcltechsw.com/resources/us-government-contact\">https://hcltechsw.com /resources/us-government-contact</a>. Ikke inkluder noen personopplysninger i denne kommentarboksen.',
        "rating.check.note": '<b>Merk:</b> For å rapportere et problem eller spørsmål om produktprogramvaren, ikke bruk dette skjemaet. Gå i stedet til <a href=\"https://support.hcltechsw.com/csm\">HCL Software Support</a>-siden.',
		"rating.check.privacy": 'Personopplysninger skal ikke deles i dette kommentarfeltet. Se vår <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">personvernerklæring</a> for å forstå hvordan personopplysninger brukes.',
        "request.version.error": "Siden er ikke tilgjengelig for den valgte versjonen!",
        "request.language.error": "Oversettelse finnes ikke!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Produktdokumentasjon",
		"header.resource.dropdown": "Ressurser",
		"header.customer.support": "Kundeservice",
		"header.community.forums": "Fellesskapsfora",
		"feedback.comment.PII.messagealert": "Vennligst fjern personlig informasjon som e-postadresse og telefonnummer før du klikker Send.",
		"feedback.comment.alert": "Skriv inn kommentarene dine i kommentarfeltet.",
		"footer.mail.link": "Del: E-post",
		"footer.twitt.link": "Twitter",
		"footer.disclaim.label": "Ansvarsfraskrivelse",
		"footer.privacy.label": "Personvern",
		"footer.terms.label": "Vilkår for bruk",
		"footer.cookie.label": "Cookie-innstillinger"
    },
	"pt": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Selecione uma versão",
        "switcher.language.tooltip": "Selecione um idioma",
        "rating.success.alert": "Obrigado pelo seu feedback!",
		"rating.no.show": "<b>Tem feedback?</b> <br/>O Google Analytics é usado para armazenar comentários e classificações. Para fornecer um comentário ou classificação para um tópico, clique em <b>Aceitar todos os cookies</b> ou <b>permitir que todos em</b> preferências de cookies no rodapé desta página.",
        "rating.error.alert": "Para enviar comentários, primeira taxa ou comentar sobre o tema.",
        "rating.star.label": "Avalie este tópico",
        "rating.comment.label": "Comente sobre este assunto",
        "rating.check.label": 'Ao clicar nesta caixa, você reconhece que não é um funcionário ou agência do governo federal dos EUA, nem está enviando informações em relação a um ou em nome de um. A HCL fornece software e serviços para clientes do Governo Federal dos EUA através de seus parceiros Four, Inc. Entre em contato com esta equipe em <a href=\"https://hcltechsw.com/resources/us-government-contact\">https://hcltechsw.com/resources/us-government-contact</a>. Não inclua nenhum dado pessoal nesta caixa de comentários.',
        "rating.check.note": '<b>nota:</b> Para relatar um problema ou questionar sobre o software do produto, não use este formulário. Em vez disso, vá para o site de suporte de software <a href=\"https://support.hcltechsw.com/csm\">HCL</a>.',
		"rating.check.privacy": 'Os dados pessoais não devem ser compartilhados nesta caixa de comentários. Consulte nossa <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">Privacy Statement</a> para entender como os dados pessoais são usados.',
        "request.version.error": "A página não está disponível para a versão selecionada!",
        "request.language.error": "A tradução não existe!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Documentação do produto",
		"header.resource.dropdown": "Recursos",
		"header.customer.support": "Suporte ao Cliente",
		"header.community.forums": "Fóruns da Comunidade",
		"feedback.comment.PII.messagealert": "Remova informações pessoais, como seu endereço de e-mail e número de telefone, antes de clicar em Enviar.",
		"feedback.comment.alert": "Insira seus comentários na caixa de comentários.",
		"footer.mail.link": "Compartilhar: E-mail",
		"footer.twitt.link": "Gorjeio",
		"footer.disclaim.label": "Disclaimer",
		"footer.privacy.label": "Privacidade",
		"footer.terms.label": "Termos de uso",
		"footer.cookie.label": "Preferências de cookies"
    },
	 "ro": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Selectați o versiune",
        "switcher.language.tooltip": "Selectarea unei limbi",
        "rating.success.alert": "Vă mulțumim pentru feedback-ul dvs.!",
		"rating.no.show": "<b>Aveți feedback?</b> <br/>Google Analytics este utilizat pentru a stoca comentarii și evaluări. Pentru a oferi un comentariu sau o evaluare pentru un subiect, faceți clic pe <b>Acceptare toate cookie-urile</b> sau <b>pe Permitere totală</b> în preferințele privind cookie-urile în subsolul acestei pagini.",
        "rating.error.alert": "Pentru a trimite feedback, prima rată sau comentariu pe această temă.",
        "rating.star.label": "Evaluați acest subiect",
        "rating.comment.label": "Comentează acest subiect",
        "rating.check.label": 'Făcând clic pe această casetă, recunoașteți că NU sunteți angajat sau agenție a Guvernului Federal al SUA și nici nu trimiteți informații cu privire la sau în numele uneia. HCL oferă software și servicii clienților Guvernului Federal al SUA prin intermediul partenerilor săi Four, Inc. Contactați această echipă la <a href=\"https://hcltechsw.com/resources/us-government-contact\">https://hcltechsw.com/resources/us-government-contact</a>. Nu includeți date cu caracter personal în această casetă Comentariu.',
        "rating.check.note": '<b>notă:</b> Pentru a raporta o problemă sau o întrebare despre software-ul produsului, nu utilizați acest formular. În schimb, accesați site-ul <a href=\"https://support.hcltechsw.com/csm\">HCL Software Support</a>.',
		"rating.check.privacy": 'Datele cu caracter personal nu ar trebui să fie partajate în această casetă de comentarii. Consultați <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">Declarația de confidențialitate</a> pentru a înțelege modul în care sunt utilizate datele cu caracter personal.',
        "request.version.error": "Pagina nu este disponibilă pentru versiunea selectată!",
        "request.language.error": "Traducerea nu există!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Documentația produsului",
		"header.resource.dropdown": "Resurse",
		"header.customer.support": "Asistenţă",
		"header.community.forums": "Forumuri comunitare",
		"feedback.comment.PII.messagealert": "Vă rugăm să eliminați informațiile personale, cum ar fi adresa de e-mail și numărul de telefon înainte de a face clic pe Trimitere.",
		"feedback.comment.alert": "Introduceți comentariile în caseta de comentarii.",
		"footer.mail.link": "Partajare: E-mail",
		"footer.twitt.link": "Twitter",
		"footer.disclaim.label": "Disclaimer",
		"footer.privacy.label": "Intimitate",
		"footer.terms.label": "Termeni de utilizare",
		"footer.cookie.label": "Preferințe cookie-uri"
    },
	"sk": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Vyberte verziu",
        "switcher.language.tooltip": "Vyberte jazyk",
        "rating.success.alert": "Ďakujeme vám za vašu reakciu!",
		"rating.no.show": "<b>Máte spätnú väzbu?</b><br/>Google Analytics sa používa na ukladanie komentárov a hodnotení. Ak chcete pridať komentár alebo hodnotenie k téme, kliknite na položku <b>Prijať všetky súbory cookie</b> alebo <b>Povoliť všetko</b> v časti Predvoľby súborov cookie v päte tejto stránky.",
        "rating.error.alert": "Ak chcete odoslať spätnú väzbu, najprv ohodnoťte alebo komentujte tému.",
        "rating.star.label": "Ohodnoťte túto tému",
        "rating.comment.label": "Komentujte túto tému",
        "rating.check.label": 'Kliknutím na toto políčko beriete na vedomie, že NIE ste zamestnancom alebo agentúrou federálnej vlády USA, ani neposielate informácie v súvislosti s nimi alebo v ich mene. HCL poskytuje softvér a služby zákazníkom federálnej vlády USA prostredníctvom svojich partnerov Four, Inc. Kontaktujte tento tím na <a href=\"https://hcltechsw.com/resources/us-government-contact\">https://hcltechsw.com /resources/us-government-contact</a>. Do tohto poľa komentára neuvádzajte žiadne osobné údaje.',
        "rating.check.note": '<b>Poznámka:</b> Ak chcete nahlásiť problém alebo otázku týkajúcu sa softvéru produktu, nepoužívajte tento formulár. Namiesto toho prejdite na stránku <a href=\"https://support.hcltechsw.com/csm\">HCL Software Support</a>.',
		"rating.check.privacy": 'V tomto poli komentárov by sa nemali zdieľať osobné údaje. Ak chcete pochopiť, ako sa používajú osobné údaje, pozrite si naše <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">Vyhlásenie o ochrane osobných údajov</a>.',
        "request.version.error": "Stránka nie je dostupná pre zvolenú verziu!",
        "request.language.error": "Preklad neexistuje!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Produktová dokumentácia",
		"header.resource.dropdown": "Zdroje",
		"header.customer.support": "Zákaznícka podpora",
		"header.community.forums": "komunitné fóra",
		"feedback.comment.PII.messagealert": "Pred kliknutím na Odoslať odstráňte osobné informácie, ako je vaša e-mailová adresa a telefónne číslo.",
		"feedback.comment.alert": "Do poľa komentárov zadajte svoje komentáre.",
		"footer.mail.link": "Zdieľať: Email",
		"footer.twitt.link": "Twitter",
		"footer.disclaim.label": "Vylúčenie zodpovednosti",
		"footer.privacy.label": "Ochrana osobných údajov",
		"footer.terms.label": "Podmienky používania",
		"footer.cookie.label": "Predvoľby súborov cookie"
    },
	"sl": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Izberite različico",
        "switcher.language.tooltip": "Izberite jezik",
        "rating.success.alert": "Hvala za vaše mnenje!",
		"rating.no.show": "<b>Imate povratne informacije?</b><br/>Google Analytics se uporablja za shranjevanje komentarjev in ocen. Če želite dati komentar ali oceno za temo, kliknite <b>Sprejmi vse piškotke</b> ali <b>Dovoli vse</b> v nastavitvah piškotkov v nogi te strani.",
        "rating.error.alert": "Če želite poslati povratne informacije, najprej ocenite ali komentirajte temo.",
        "rating.star.label": "Ocenite to temo",
        "rating.comment.label": "Komentirajte to temo",
        "rating.check.label": 'S klikom na to polje potrjujete, da NISTE uslužbenec ali agencija zvezne vlade ZDA, niti ne pošiljate informacij v zvezi z njim ali v njegovem imenu. HCL zagotavlja programsko opremo in storitve strankam zvezne vlade ZDA prek svojih partnerjev Four, Inc. Obrnite se na to ekipo na <a href=\"https://hcltechsw.com/resources/us-government-contact\">https://hcltechsw.com /resources/us-government-contact</a>. V to polje za komentar ne vključujte nobenih osebnih podatkov.',
        "rating.check.note": '<b>Opomba:</b> Če želite prijaviti težavo ali vprašanje o programski opremi izdelka, ne uporabljajte tega obrazca. Namesto tega pojdite na spletno mesto <a href=\"https://support.hcltechsw.com/csm\">Podpora za programsko opremo HCL</a>.',
		"rating.check.privacy": 'Osebnih podatkov ne smete deliti v tem polju za komentarje. Če želite razumeti, kako se uporabljajo osebni podatki, si oglejte našo <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">izjavo o zasebnosti</a>.',
        "request.version.error": "Stran ni na voljo za izbrano različico!",
        "request.language.error": "Prevod ne obstaja!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Dokumentacija izdelka",
		"header.resource.dropdown": "Viri",
		"header.customer.support": "Pomoč strankam",
		"header.community.forums": "Forumi skupnosti",
		"feedback.comment.PII.messagealert": "Preden kliknete Pošlji, odstranite osebne podatke, kot sta vaš e-poštni naslov in telefonska številka.",
		"feedback.comment.alert": "Vnesite svoje komentarje v polje za komentarje.",
		"footer.mail.link": "Deli: E-pošta",
		"footer.twitt.link": "Twitter",
		"footer.disclaim.label": "Zavrnitev odgovornosti",
		"footer.privacy.label": "Zasebnost",
		"footer.terms.label": "Pogoji uporabe",
		"footer.cookie.label": "Nastavitve piškotkov"
    },
	"sv": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Välj en version",
        "switcher.language.tooltip": "Välj ett språk",
        "rating.success.alert": "Tack för din feedback!",
		"rating.no.show": "<b>Har du feedback?</b><br/>Google Analytics används för att lagra kommentarer och betyg. För att ge en kommentar eller betyg för ett ämne, klicka på <b>Acceptera alla cookies</b> eller <b>Tillåt alla</b> i Cookie-inställningar i sidfoten på den här sidan.",
        "rating.error.alert": "För att skicka feedback, först betygsätt eller kommentera ämnet.",
        "rating.star.label": "Betygsätt detta ämne",
        "rating.comment.label": "Kommentera om detta ämne",
        "rating.check.label": 'Genom att klicka på den här rutan bekräftar du att du INTE är anställd eller byrå i USA:s federala regering, och att du inte heller skickar information med avseende på eller på uppdrag av någon. HCL tillhandahåller programvara och tjänster till kunder i den amerikanska federala regeringen genom sina partners Four, Inc. Kontakta detta team på <a href=\"https://hcltechsw.com/resources/us-government-contact\">https://hcltechsw.com /resources/us-government-contact</a>. Inkludera inga personuppgifter i denna kommentarsruta.',
        "rating.check.note": '<b>Obs!</b> Använd inte det här formuläret för att rapportera ett problem eller en fråga om produktprogramvaran. Gå istället till webbplatsen <a href=\"https://support.hcltechsw.com/csm\">HCL Software Support</a>.',
		"rating.check.privacy": 'Personuppgifter ska inte delas i detta kommentarsfält. Se vår <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">sekretesspolicy</a> för att förstå hur personuppgifter används.',
        "request.version.error": "Sidan är inte tillgänglig för den valda versionen!",
        "request.language.error": "Översättning finns inte!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Produktdokumentation",
		"header.resource.dropdown": "Resurser",
		"header.customer.support": "Kundsupport",
		"header.community.forums": "Gemenskapsforum",
		"feedback.comment.PII.messagealert": "Ta bort personlig information som din e-postadress och ditt telefonnummer innan du klickar på Skicka.",
		"feedback.comment.alert": "Skriv dina kommentarer i kommentarsfältet.",
		"footer.mail.link": "Dela: E-post",
		"footer.twitt.link": "Twitter",
		"footer.disclaim.label": "varning",
		"footer.privacy.label": "Integritet",
		"footer.terms.label": "Villkor",
		"footer.cookie.label": "Cookie-inställningar"
    },
	 "tr": {
		"pdf.icon.tooltip": "",
        "switcher.version.tooltip": "Bir sürüm seçin",
        "switcher.language.tooltip": "Bir dil seçin",
        "rating.success.alert": "Geri bildiriminiz için teşekkür ederiz!",
		"rating.no.show": "<b>Geri bildiriminiz mi var?</b> <br/>Google Analytics, yorumları ve derecelendirmeleri depolamak için kullanılır. Bir konu için yorum veya derecelendirme sağlamak üzere bu sayfanın altbilgisinde <b>Tüm Çerezleri Kabul Et</b> veya Çerez Tercihlerinde Tümüne <b>İzin Ver\'i</b> tıklatın.",
        "rating.error.alert": "Geri bildirim göndermek için, konuyla ilgili birinci sınıf veya yorum yapın.",
        "rating.star.label": "Bu konuyu derecelendirin",
        "rating.comment.label": "Bu konu hakkında yorum yapın",
        "rating.check.label": 'Bu kutuyu tıklayarak, bir ABD Federal Hükümeti çalışanı veya kurumu OLMADIĞINIZI ve bir kurumla ilgili veya onun adına bilgi göndermediğinizi kabul edersiniz. HCL, ortakları Four, Inc>https://hcltechsw.com/resources/us-government-contact https://hcltechsw.com/resources/us-government-contact<. aracılığıyla ABD Federal Hükümeti müşterilerine yazılım ve hizmetler sunmaktadır.</a> Bu Yorum kutusuna herhangi bir kişisel veri eklemeyin.',
        "rating.check.note": '<b>not:</b> Ürün yazılımıyla ilgili bir sorunu veya soruyu bildirmek için bu formu kullanmayın. Bunun yerine, <a href=\"https://support.hcltechsw.com/csm\">HCL Yazılım Desteği sitesine gidin</a>.',
		"rating.check.privacy": 'Kişisel veriler bu yorum kutusunda paylaşılmamalıdır. Kişisel verilerin nasıl kullanıldığını anlamak için <a href=\"https://www.hcltechsw.com/legal/privacy\" target=\"_block\">Gizlilik Bildirimimize bakın</a>.',
        "request.version.error": "Sayfa seçilen sürüm için mevcut değil!",
        "request.language.error": "Çeviri yok!",
        "header.learning.academy": "HCLSoftware U",
		"header.proddoc.brand": "Ürün Belgeleri",
		"header.resource.dropdown": "Kaynaklar",
		"header.customer.support": "Müşteri Desteği",
		"header.community.forums": "Topluluk Forumları",
		"feedback.comment.PII.messagealert": "Lütfen Gönder\'i tıklamadan önce e-posta adresiniz ve telefon numaranız gibi kişisel bilgileri kaldırın.",
		"feedback.comment.alert": "Yorum kutusuna yorumlarınızı girin.",
		"footer.mail.link": "Paylaş: E-posta",
		"footer.twitt.link": "Heyecan",
		"footer.disclaim.label": "Feragatname",
		"footer.privacy.label": "Gizlilik",
		"footer.terms.label": "Kullanım koşulları",
		"footer.cookie.label": "Çerez Tercihleri"
    }
 }
 